version: '3.8'

services:

  nodejs:
    build:
      context: nodejs
      args:
        - ID_GROUP=${ID_GROUP}
        - ID_USER=${ID_USER}
        - NODE_VERSION=${NODE_VERSION}
    working_dir: /usr/share/nginx/frontend
    volumes:
      - ../frontend:/usr/share/nginx/frontend
    environment:
      - HOST=0.0.0.0
    user: "${ID_USER}:${ID_GROUP}"

  nodejs_dev:
    build:
      context: nodejs
      args:
        - ID_GROUP=${ID_GROUP}
        - ID_USER=${ID_USER}
        - NODE_VERSION=${NODE_VERSION}
    working_dir: /usr/share/nginx/frontend
    volumes:
      - ../frontend:/usr/share/nginx/frontend
    environment:
      - HOST=0.0.0.0
    user: "${ID_USER}:${ID_GROUP}"
    command: tail -F anything
    restart: unless-stopped
    ports:
      - "24678:24678" # for vite websocket
    profiles:
      - dev

  nginx_dev:
    build:
      context: nginx_dev
      args:
        - NGINX_VERSION=${NGINX_VERSION}
    working_dir: /usr/share/nginx/backend
    volumes:
      - ../backend:/usr/share/nginx/backend
      - ../frontend:/usr/share/nginx/frontend
    restart: unless-stopped
    ports:
      - ${PORT_NGINX}:80
    profiles:
      - dev

  nginx_prod:
    build:
      context: nginx_prod
      args:
        - NGINX_VERSION=${NGINX_VERSION}
    working_dir: /usr/share/nginx/backend
    volumes:
      - ../backend:/usr/share/nginx/backend
      - ../frontend:/usr/share/nginx/frontend
    restart: unless-stopped
    ports:
      - ${PORT_NGINX}:80
    profiles:
      - prod

  php:
    build:
      context: php
      args:
        - PHP_VERSION=${PHP_VERSION}
        - COMPOSER_VERSION=${COMPOSER_VERSION}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
        - PORT_XDEBUG=${PORT_XDEBUG}
        - ID_GROUP=${ID_GROUP}
        - ID_USER=${ID_USER}
        - DOCKERHOST=${DOCKERHOST}
    working_dir: /usr/share/nginx/backend
    volumes:
      - ../backend:/usr/share/nginx/backend
    command: bash -c "service php${PHP_VERSION}-fpm start && tail -F anything"
    environment:
      PHP_IDE_CONFIG: "serverName=${PHP_IDE_CONFIG_SERVER_NAME}"
    restart: unless-stopped

  mysql:
    build:
      context: mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./databases/mysql:/var/lib/mysql
      - ../backend:/usr/share/nginx/backend
    ports:
      - ${PORT_MYSQL}:3306
    working_dir: /usr/share/nginx/backend

  cron:
    build:
      context: cron
      args:
        - PHP_VERSION=${PHP_VERSION}
    working_dir: /usr/share/nginx/backend
    volumes:
      - ../backend:/usr/share/nginx/backend
    command: bash -c "cron && tail -F anything"
    restart: unless-stopped
