version: '3.8'

services:

  nodejs:
    build:
      context: nodejs
      args:
        - ID_GROUP=${ID_GROUP}
        - ID_USER=${ID_USER}
        - NODE_VERSION=${NODE_VERSION}
    command: bash -c "tail -F anything"
    working_dir: /usr/share/nginx/html
    volumes:
      - ../frontend:/usr/share/nginx/html
    environment:
      - HOST=0.0.0.0
    user: "${ID_USER}:${ID_GROUP}"

  nginx:
    build:
      context: nginx
      args:
        - NGINX_VERSION=${NGINX_VERSION}
    volumes:
      - ../backend:/usr/share/nginx/html
    restart: unless-stopped
    ports:
      - ${PORT_NGINX}:80
