FROM ubuntu:20.04

ARG PHP_VERSION=8.1
RUN apt-get update &&\
    apt-get install software-properties-common -y &&\
    add-apt-repository ppa:ondrej/php -y &&\
    apt-get update
#    apt-get update\
#    apt-get install\
#    		php${PHP_VERSION}\
#				php${PHP_VERSION}-cli\


