# Do not edit. Generated by the configure script.
export PATH:=/usr/share/nginx/html/node-v16.14.2/out/tools/bin:$(PATH)
BUILDTYPE=Release
NODE_TARGET_TYPE=executable
PYTHON=/usr/bin/python3.8
PREFIX=/usr/local
